// Business contact details. GENERATED by `python3 site_config.py`; edit site_config.py.
export const PHONE = "8296548156";
export const EMAIL = "info@fullstackverse.in";
export const ADDRESS_LINES = ["Digital Innovation Hub", "India"];

// Main-site WhatsApp chat (header, footer).
export const WHATSAPP_URL =
  "https://wa.me/918296548156?text=Hello%20Fullstackverse,%20I%27d%20like%20to%20discuss%20my%20project%20idea.";

// SkillVerse uses a second line for calls from its header.
export const SKILLVERSE_CALL = "7042709578";
export const SKILLVERSE_WHATSAPP_URL =
  "https://wa.me/918296548156?text=Hello%20SkillVerse,%20I%27d%20like%20to%20learn%20more%20about%20your%20courses.";
