// Fullstackverse portfolio: concept projects designed by the Fullstackverse
// team to show the kind of products we build. They are product concepts,
// not client engagements, so no client names or results are claimed.
//
// shots: which demo-dashboard screenshot (public/portfolio/<slug>-<n>.webp, made by
//   `npm run screens`) is the hero/card image and which illustrates key features.

export const PORTFOLIO_CATEGORIES = ['All', 'AI & Computer Vision', 'E-commerce', 'Mobile Apps', 'Enterprise Software', 'Websites', 'Games'];

export const projects = [
  {
    slug: 'sparesphere-industrial-parts-marketplace',
    name: 'SpareSphere',
    title: 'B2B marketplace for heavy-equipment spare parts',
    category: 'E-commerce',
    industry: 'Industrial Supplies',
    platforms: ['Web App', 'Admin Panel'],
    accent: '#1F3C88',
    shots: { hero: 3, feature: 2 },
    summary:
      'SpareSphere is a B2B ordering platform for construction and mining equipment parts. Fleet operators find the exact part by machine model or part number, request bulk quotes, and track every order from warehouse to site, while suppliers manage stock across multiple depots from one dashboard.',
    stack: ['React', 'Node.js', 'PostgreSQL', 'Elasticsearch', 'Razorpay', 'AWS'],
    challenges: [
      { title: 'Hard-to-find parts', text: 'Buyers search by machine model, serial number or OEM code, and a plain keyword search returns the wrong fit.' },
      { title: 'Quotes over email', text: 'Bulk and urgent orders are negotiated over email and calls, so pricing is slow and inconsistent.' },
      { title: 'Stock spread across depots', text: 'Inventory sits in several warehouses with no single, live view of what can actually ship today.' },
      { title: 'No order visibility', text: 'Site managers have no way to see dispatch status, so they chase suppliers for updates.' },
      { title: 'Credit and GST billing', text: 'Business buyers need credit terms, GST invoices and approval flows that a retail checkout does not handle.' },
      { title: 'Warranty paperwork', text: 'Part certificates and warranty documents are stored on paper and are hard to retrieve after delivery.' },
    ],
    solutions: [
      { title: 'Fitment-aware search', text: 'Search and filter by equipment brand, model and part number, with compatible alternatives suggested automatically.' },
      { title: 'Request-for-quote workflow', text: 'Buyers raise RFQs for bulk orders; suppliers respond with pricing and lead times inside the platform.' },
      { title: 'Multi-depot inventory', text: 'Live stock across every warehouse, with orders routed to the depot nearest the delivery site.' },
      { title: 'Business accounts', text: 'Company profiles with multiple buyers, approval limits, credit terms and automatic GST invoices.' },
    ],
    features: [
      { title: 'Part finder by machine model', text: 'Pick the machine once and only see parts that fit it.' },
      { title: 'Bulk quote requests', text: 'Upload a parts list and receive a consolidated quotation.' },
      { title: 'Order and dispatch tracking', text: 'Status updates from packing to delivery at site.' },
      { title: 'Digital document vault', text: 'Certificates, invoices and warranty cards attached to every order.' },
      { title: 'Supplier dashboard', text: 'Stock, pricing, quotes and orders managed from one screen.' },
    ],
    outcomes: [
      { title: 'Faster procurement', text: 'Buyers move from search to purchase order without back-and-forth emails.' },
      { title: 'Accurate stock', text: 'One live inventory view reduces cancelled and delayed orders.' },
      { title: 'Less manual work', text: 'Quotes, invoices and documents are generated automatically.' },
      { title: 'Ready to scale', text: 'New suppliers, depots and categories can be added without rework.' },
    ],
  },
  {
    slug: 'vigilo-ai-safety-monitoring',
    name: 'Vigilo',
    title: 'AI CCTV analytics for warehouse and factory safety',
    category: 'AI & Computer Vision',
    industry: 'Manufacturing & Warehousing',
    platforms: ['Web Dashboard', 'Edge AI', 'Mobile Alerts'],
    accent: '#0F766E',
    shots: { hero: 2, feature: 3 },
    summary:
      'Vigilo turns existing CCTV cameras into a safety assistant. Computer-vision models watch live feeds for missing helmets and vests, forklift near-misses, blocked fire exits and smoke, and send instant alerts to supervisors with a short clip of the event.',
    stack: ['Python', 'PyTorch', 'YOLO', 'OpenCV', 'FastAPI', 'React', 'NVIDIA Jetson'],
    challenges: [
      { title: 'Too many screens to watch', text: 'Security staff cannot watch dozens of camera feeds at once, so incidents are missed.' },
      { title: 'PPE rules ignored', text: 'Helmets, vests and gloves are skipped on busy shifts and nobody notices until an accident.' },
      { title: 'Forklift and pedestrian risk', text: 'Vehicles and people share aisles, and near-misses go unrecorded.' },
      { title: 'Blocked exits', text: 'Pallets left in front of fire exits and walkways are a hidden compliance risk.' },
      { title: 'Slow emergency response', text: 'Smoke and fire are often spotted late, losing critical minutes.' },
      { title: 'No safety data', text: 'Without records, managers cannot see which zones or shifts carry the most risk.' },
    ],
    solutions: [
      { title: 'Works with existing cameras', text: 'Connects to standard IP/RTSP cameras, so no new CCTV hardware is needed.' },
      { title: 'Real-time vision models', text: 'Models detect PPE, vehicles, people, smoke and obstructions on every frame.' },
      { title: 'Instant alerts with evidence', text: 'Supervisors get a WhatsApp, SMS or app alert with a snapshot and short clip.' },
      { title: 'Safety analytics', text: 'Dashboards show violations by zone, shift and type to target training.' },
    ],
    features: [
      { title: 'PPE compliance detection', text: 'Helmet, vest, mask and glove checks per camera zone.' },
      { title: 'Forklift proximity alerts', text: 'Warns when people and vehicles come too close.' },
      { title: 'Fire and smoke detection', text: 'Early visual detection before smoke alarms trigger.' },
      { title: 'Restricted zone intrusion', text: 'Alerts when someone enters a no-go area.' },
      { title: 'Blocked exit monitoring', text: 'Flags objects left in exits and walkways.' },
    ],
    outcomes: [
      { title: 'Safer floors', text: 'Unsafe behaviour is caught as it happens, not after an incident.' },
      { title: 'Less manual monitoring', text: 'Staff respond to alerts instead of watching screens all day.' },
      { title: 'Audit-ready records', text: 'Every event is logged with time, place and footage.' },
      { title: 'Data-driven training', text: 'Clear trends show where safety coaching is needed.' },
    ],
  },
  {
    slug: 'framewise-video-annotation-platform',
    name: 'Framewise',
    title: 'Video annotation studio for training vision AI models',
    category: 'AI & Computer Vision',
    industry: 'AI & Data',
    platforms: ['Web App', 'Review Portal'],
    accent: '#7C3AED',
    shots: { hero: 2, feature: 3 },
    summary:
      'Framewise is a collaborative tool for labelling video data. Teams draw boxes and polygons, track objects across frames, and review each other\'s work, then export clean datasets in standard formats ready for model training.',
    stack: ['React', 'TypeScript', 'Canvas API', 'Python', 'Django', 'PostgreSQL', 'S3'],
    challenges: [
      { title: 'Frame-by-frame labelling', text: 'Labelling every frame by hand makes video datasets slow and expensive to build.' },
      { title: 'Inconsistent labels', text: 'Different annotators label the same object differently, which hurts model accuracy.' },
      { title: 'Large video files', text: 'Long, high-resolution footage is hard to load, scrub and share in the browser.' },
      { title: 'No review process', text: 'There is no simple way to check, correct and approve annotations before training.' },
      { title: 'Format conversion', text: 'Every training framework expects a different export format.' },
      { title: 'Tracking progress', text: 'Managers cannot see which clips are done, pending or rejected.' },
    ],
    solutions: [
      { title: 'Object tracking between frames', text: 'Label once and the tool interpolates the box across following frames for quick correction.' },
      { title: 'Shared label schemas', text: 'Projects define classes and rules up front so every annotator labels the same way.' },
      { title: 'Review and approval queue', text: 'Reviewers accept, fix or reject work with comments on the exact frame.' },
      { title: 'One-click exports', text: 'Export datasets as COCO, YOLO or Pascal VOC with train/validation splits.' },
    ],
    features: [
      { title: 'Boxes, polygons and keypoints', text: 'All common annotation types in one editor.' },
      { title: 'Smooth video player', text: 'Frame stepping, zoom and playback speed for precise work.' },
      { title: 'Model-assisted pre-labels', text: 'Optional AI suggestions that annotators confirm or adjust.' },
      { title: 'Team roles', text: 'Annotator, reviewer and admin permissions per project.' },
      { title: 'Progress dashboard', text: 'Clips, labels and quality scores at a glance.' },
    ],
    outcomes: [
      { title: 'Quicker datasets', text: 'Tracking and pre-labels cut the clicks needed per clip.' },
      { title: 'Cleaner training data', text: 'Shared rules and review improve label consistency.' },
      { title: 'Smooth handover', text: 'Datasets export straight into the training pipeline.' },
      { title: 'Clear ownership', text: 'Everyone knows what to label and what to review next.' },
    ],
  },
  {
    slug: 'respira-ai-respiratory-screening',
    name: 'Respira',
    title: 'AI respiratory sound screening app for clinics',
    category: 'AI & Computer Vision',
    industry: 'Healthcare',
    platforms: ['Android App', 'iOS App', 'Doctor Portal'],
    accent: '#0369A1',
    shots: { hero: 2, feature: 3 },
    summary:
      'Respira helps clinics in small towns screen patients for respiratory problems. A health worker records breathing and cough sounds on a phone, the app shows a clear sound visual and an AI screening hint, and the recording is shared securely with a doctor for review.',
    stack: ['Flutter', 'TensorFlow Lite', 'Python', 'FastAPI', 'PostgreSQL', 'AWS'],
    challenges: [
      { title: 'Few specialists', text: 'Rural clinics rarely have a chest specialist on site to listen and interpret sounds.' },
      { title: 'Nothing is recorded', text: 'A normal stethoscope check leaves no recording to compare or share later.' },
      { title: 'Subjective listening', text: 'Interpretation depends on the listener\'s experience and the noise in the room.' },
      { title: 'Slow referrals', text: 'Sending a patient to a city doctor just for a second opinion costs time and money.' },
      { title: 'Patient privacy', text: 'Health recordings must be stored and shared securely with consent.' },
      { title: 'Low connectivity', text: 'Clinics need the app to work even when the internet is patchy.' },
    ],
    solutions: [
      { title: 'Guided recording', text: 'Step-by-step prompts show where and how long to record for a usable sample.' },
      { title: 'Visual sound analysis', text: 'Recordings are shown as waveforms and spectrograms that are easy to read and compare.' },
      { title: 'On-device AI screening', text: 'A lightweight model flags recordings that may need a doctor\'s attention, even offline.' },
      { title: 'Secure doctor review', text: 'Encrypted sharing to a doctor portal for remote review and notes.' },
    ],
    features: [
      { title: 'Patient profiles', text: 'History of recordings and notes per patient.' },
      { title: 'Noise check', text: 'Warns when background noise makes a recording unreliable.' },
      { title: 'Offline queue', text: 'Records offline and syncs when the connection returns.' },
      { title: 'Doctor portal', text: 'Review queue, playback and written recommendations.' },
      { title: 'Consent and audit log', text: 'Patient consent captured with every recording.' },
    ],
    outcomes: [
      { title: 'Earlier attention', text: 'Patients who need a doctor are identified sooner.' },
      { title: 'Shareable evidence', text: 'Recordings can be revisited and compared over time.' },
      { title: 'Fewer wasted trips', text: 'Remote review avoids unnecessary travel for patients.' },
      { title: 'Privacy by design', text: 'Encrypted storage and consent tracking from day one.' },
    ],
    note: 'Concept for a screening aid. Any medical product would need clinical validation and regulatory approval before use.',
  },
  {
    slug: 'gridmind-energy-automation-website',
    name: 'GridMind',
    title: 'Corporate website for an energy automation software company',
    category: 'Websites',
    industry: 'Energy & Utilities',
    platforms: ['Website', 'CMS'],
    accent: '#B45309',
    shots: { hero: 1, feature: 3 },
    summary:
      'A corporate website concept for a company that sells monitoring and automation software to solar parks and power utilities. The site explains complex products in plain language, showcases use cases by industry, and turns technical visitors into demo requests.',
    stack: ['Next.js', 'Tailwind CSS', 'Headless CMS', 'Vercel', 'Google Analytics'],
    challenges: [
      { title: 'Complex products', text: 'SCADA, monitoring and analytics products are hard to explain to non-engineers.' },
      { title: 'Several audiences', text: 'Plant engineers, procurement teams and executives all look for different information.' },
      { title: 'Outdated site', text: 'An old website that is slow, not mobile-friendly and hard to update.' },
      { title: 'Weak lead capture', text: 'Visitors leave without an easy way to request a demo or download specs.' },
      { title: 'Global visitors', text: 'Prospects in different countries need content in more than one language.' },
      { title: 'SEO visibility', text: 'Product pages do not rank for the searches buyers actually use.' },
    ],
    solutions: [
      { title: 'Product storytelling', text: 'Each product page leads with the problem it solves, then the features and specs.' },
      { title: 'Industry pages', text: 'Dedicated pages for solar, wind, utilities and manufacturing with relevant use cases.' },
      { title: 'Easy content updates', text: 'A headless CMS so the marketing team can publish news and case studies without developers.' },
      { title: 'Demo and download funnels', text: 'Clear calls to action, gated datasheets and a short demo request form.' },
    ],
    features: [
      { title: 'Fast, mobile-first pages', text: 'Static pages that load quickly on any device.' },
      { title: 'Multi-language support', text: 'Content ready for more than one language.' },
      { title: 'Resource library', text: 'Datasheets, brochures and whitepapers in one place.' },
      { title: 'SEO-ready structure', text: 'Clean URLs, metadata and structured data on every page.' },
      { title: 'CRM-connected forms', text: 'Leads land straight in the sales pipeline.' },
    ],
    outcomes: [
      { title: 'Clearer message', text: 'Visitors understand what the software does within seconds.' },
      { title: 'More qualified enquiries', text: 'Focused calls to action turn interest into demo requests.' },
      { title: 'Marketing independence', text: 'The team updates the site without waiting on developers.' },
      { title: 'Better search presence', text: 'Product and industry pages are built to be found.' },
    ],
  },
  {
    slug: 'bazaarly-classifieds-marketplace',
    name: 'Bazaarly',
    title: 'Local classifieds marketplace for buying and selling',
    category: 'Mobile Apps',
    industry: 'Marketplace',
    platforms: ['Android App', 'iOS App', 'Web App', 'Admin Panel'],
    accent: '#C2410C',
    shots: { hero: 2, feature: 1 },
    summary:
      'Bazaarly is a classifieds app where people post ads for used phones, furniture, vehicles, rentals and services in their city. Buyers chat with sellers in the app, and sellers can pay to promote listings for more visibility.',
    stack: ['React Native', 'Node.js', 'MongoDB', 'Firebase', 'Google Maps', 'Razorpay'],
    challenges: [
      { title: 'Fake and spam ads', text: 'Open marketplaces attract scams, duplicates and misleading listings.' },
      { title: 'Finding nearby deals', text: 'Buyers want relevant items close to them, not across the country.' },
      { title: 'Unsafe contact sharing', text: 'Sharing phone numbers publicly exposes users to spam calls.' },
      { title: 'Posting friction', text: 'Long forms discourage people from listing items.' },
      { title: 'Monetisation', text: 'The platform needs revenue without ruining the free experience.' },
      { title: 'Moderation load', text: 'Reviewing every ad manually does not scale.' },
    ],
    solutions: [
      { title: 'Verified profiles', text: 'Phone OTP sign-up, seller ratings and report buttons build trust.' },
      { title: 'Location-based browsing', text: 'Ads are sorted by distance, with category and price filters.' },
      { title: 'In-app chat', text: 'Buyers and sellers talk without revealing phone numbers.' },
      { title: 'Paid promotions', text: 'Sellers can boost or feature listings for a small fee.' },
    ],
    features: [
      { title: 'Post an ad in a minute', text: 'Photos, title, price and location in a short guided flow.' },
      { title: 'Smart categories', text: 'Category-specific fields for cars, property, jobs and more.' },
      { title: 'Saved searches and alerts', text: 'Get notified when a matching item is posted.' },
      { title: 'Moderation tools', text: 'Auto-flagging plus an admin review queue.' },
      { title: 'Seller dashboard', text: 'Views, chats and promotion performance per ad.' },
    ],
    outcomes: [
      { title: 'Trusted marketplace', text: 'Verification and moderation keep listings genuine.' },
      { title: 'Higher engagement', text: 'Nearby results and alerts bring users back.' },
      { title: 'Revenue stream', text: 'Promotions monetise the platform fairly.' },
      { title: 'Scalable moderation', text: 'Automation handles the routine, people handle the edge cases.' },
    ],
  },
  {
    slug: 'buildbridge-contractor-network-app',
    name: 'BuildBridge',
    title: 'App connecting homeowners with verified contractors',
    category: 'Mobile Apps',
    industry: 'Construction & Home Services',
    platforms: ['Android App', 'iOS App', 'Admin Panel'],
    accent: '#A16207',
    shots: { hero: 3, feature: 2 },
    summary:
      'BuildBridge helps homeowners find trusted masons, electricians, plumbers and interior contractors nearby. Customers compare profiles, past work and ratings, request quotes, and track the job, while contractors get a steady stream of local leads.',
    stack: ['Flutter', 'Firebase', 'Node.js', 'PostgreSQL', 'Google Maps', 'Razorpay'],
    challenges: [
      { title: 'Finding reliable workers', text: 'Homeowners rely on word of mouth and have no way to check a contractor\'s track record.' },
      { title: 'Unclear pricing', text: 'Quotes are verbal and hard to compare between contractors.' },
      { title: 'Contractors lack leads', text: 'Skilled tradespeople depend on middlemen to find work.' },
      { title: 'Poor communication', text: 'Updates happen over scattered calls and messages.' },
      { title: 'No proof of work', text: 'Photos of past projects are scattered across phones.' },
      { title: 'Payment disputes', text: 'Advance payments without milestones lead to disagreements.' },
    ],
    solutions: [
      { title: 'Verified contractor profiles', text: 'ID checks, skills, service areas and a gallery of past work.' },
      { title: 'Structured quote requests', text: 'Customers describe the job once and receive comparable quotes.' },
      { title: 'Job tracking', text: 'Milestones, photos and chat keep both sides updated.' },
      { title: 'Milestone payments', text: 'Pay in stages as work is completed and approved.' },
    ],
    features: [
      { title: 'Search by trade and area', text: 'Find electricians, plumbers or painters near you.' },
      { title: 'Ratings and reviews', text: 'Honest feedback after every completed job.' },
      { title: 'Portfolio gallery', text: 'Contractors showcase their best work.' },
      { title: 'In-app chat and calls', text: 'Discuss details without sharing personal numbers.' },
      { title: 'Lead inbox for contractors', text: 'New requests, quotes and jobs in one place.' },
    ],
    outcomes: [
      { title: 'Confident hiring', text: 'Homeowners choose based on proof, not guesswork.' },
      { title: 'More work for tradespeople', text: 'Contractors reach customers directly.' },
      { title: 'Fewer disputes', text: 'Milestones and records keep expectations clear.' },
      { title: 'Organised projects', text: 'Every update lives in one timeline.' },
    ],
  },
  {
    slug: 'casaloom-home-decor-store',
    name: 'Casaloom',
    title: 'Direct-to-consumer online store for home décor',
    category: 'E-commerce',
    industry: 'Retail',
    platforms: ['Web Store', 'Admin Panel'],
    accent: '#9D174D',
    shots: { hero: 1, feature: 2 },
    summary:
      'Casaloom is an online store concept for a home décor brand selling cushions, rugs, lamps and tableware. It focuses on beautiful product pages, shopping by room and style, quick checkout, and simple tools for the team to run offers and manage stock.',
    stack: ['Next.js', 'Shopify Storefront API', 'Tailwind CSS', 'Algolia', 'Razorpay'],
    challenges: [
      { title: 'Products need context', text: 'Décor sells on looks, and plain product grids do not show how items fit in a room.' },
      { title: 'Cart abandonment', text: 'Long checkouts and surprise shipping costs make shoppers leave.' },
      { title: 'Slow mobile pages', text: 'Heavy images make pages slow on phones, where most shoppers browse.' },
      { title: 'Variants and stock', text: 'Colours, sizes and sets are hard to manage across channels.' },
      { title: 'Repeat customers', text: 'No easy way to bring shoppers back after their first order.' },
      { title: 'Returns handling', text: 'Fragile items need a clear, simple return process.' },
    ],
    solutions: [
      { title: 'Shop by room and style', text: 'Curated collections like Living Room or Boho help shoppers discover sets.' },
      { title: 'Fast image delivery', text: 'Optimised, lazy-loaded images keep pages quick on mobile.' },
      { title: 'One-page checkout', text: 'Address, delivery and payment on a single screen with UPI and COD.' },
      { title: 'Loyalty and reminders', text: 'Wishlists, back-in-stock alerts and reward points for repeat orders.' },
    ],
    features: [
      { title: 'Look-book pages', text: 'Styled room photos with shoppable products.' },
      { title: 'Instant search', text: 'Results as you type, with filters for colour and price.' },
      { title: 'Wishlist and alerts', text: 'Save items and get notified when they are back.' },
      { title: 'Order tracking', text: 'Delivery status and easy returns from the account page.' },
      { title: 'Offer manager', text: 'Coupons, bundles and festive sales without code changes.' },
    ],
    outcomes: [
      { title: 'Inspiring shopping', text: 'Room-based browsing helps shoppers buy complete looks.' },
      { title: 'Smoother checkout', text: 'Fewer steps mean fewer abandoned carts.' },
      { title: 'Repeat business', text: 'Loyalty tools bring customers back.' },
      { title: 'Easy operations', text: 'The team runs offers and stock from one dashboard.' },
    ],
  },
  {
    slug: 'pipetrack-sales-activity-tracker',
    name: 'PipeTrack',
    title: 'Sales team activity and performance tracker',
    category: 'Enterprise Software',
    industry: 'B2B Sales',
    platforms: ['Web App', 'Android App'],
    accent: '#1F3C88',
    shots: { hero: 2, feature: 3 },
    summary:
      'PipeTrack gives sales and pre-sales teams one place to log meetings, demos and proposals, and gives managers a live view of activity, pipeline and targets. It replaces scattered spreadsheets and end-of-week status emails.',
    stack: ['React', 'Node.js', 'PostgreSQL', 'Redis', 'Chart.js', 'Google Workspace API'],
    challenges: [
      { title: 'Spreadsheet reporting', text: 'Activities are tracked in personal sheets that never match.' },
      { title: 'No real-time view', text: 'Managers only learn about progress in weekly meetings.' },
      { title: 'Unclear targets', text: 'Team members cannot see how they are tracking against goals.' },
      { title: 'Lost follow-ups', text: 'Promised follow-ups slip because there are no reminders.' },
      { title: 'Manual approvals', text: 'Discounts and proposals are approved over email chains.' },
      { title: 'Field visits unverified', text: 'Customer visits are hard to confirm and record.' },
    ],
    solutions: [
      { title: 'Quick activity logging', text: 'Log a call, demo or visit in seconds from web or phone.' },
      { title: 'Live manager dashboards', text: 'Team activity, pipeline value and target progress in real time.' },
      { title: 'Reminders and tasks', text: 'Automatic follow-up reminders for every open opportunity.' },
      { title: 'Approval workflows', text: 'Proposals and discounts routed to the right approver.' },
    ],
    features: [
      { title: 'Calendar sync', text: 'Meetings pulled in from Google or Outlook calendars.' },
      { title: 'Check-in for visits', text: 'Location-stamped check-ins for field meetings.' },
      { title: 'Target tracking', text: 'Monthly and quarterly goals per person and team.' },
      { title: 'Leaderboards', text: 'Friendly visibility of top performers.' },
      { title: 'Export and reports', text: 'One-click reports for reviews and leadership.' },
    ],
    outcomes: [
      { title: 'One source of truth', text: 'Everyone works from the same live data.' },
      { title: 'Fewer missed follow-ups', text: 'Reminders keep deals moving.' },
      { title: 'Less reporting time', text: 'Dashboards replace manual status updates.' },
      { title: 'Better coaching', text: 'Managers see where each person needs support.' },
    ],
  },
  {
    slug: 'kalaghar-artisan-jewellery-store',
    name: 'Kalaghar',
    title: 'Online store for handcrafted artisan jewellery',
    category: 'E-commerce',
    industry: 'Fashion & Handicrafts',
    platforms: ['Web Store', 'Artisan Portal'],
    accent: '#B91C1C',
    shots: { hero: 1, feature: 2 },
    summary:
      'Kalaghar brings handcrafted silver, brass and terracotta jewellery from Indian artisans to shoppers online. Each product tells the maker\'s story, and artisans manage their own listings and orders through a simple portal.',
    stack: ['React', 'Node.js', 'MongoDB', 'Cloudinary', 'Razorpay', 'Shiprocket'],
    challenges: [
      { title: 'Artisans offline', text: 'Many makers have no online presence and rely on local fairs.' },
      { title: 'Telling the craft story', text: 'Handmade value is lost in a generic product listing.' },
      { title: 'Unique, one-off pieces', text: 'Limited stock and one-of-a-kind items complicate inventory.' },
      { title: 'Shipping fragile items', text: 'Delicate pieces need careful packing and reliable couriers.' },
      { title: 'Trust in quality', text: 'Shoppers worry about authenticity and material quality.' },
      { title: 'Payments to makers', text: 'Artisans need clear, timely payouts for each sale.' },
    ],
    solutions: [
      { title: 'Maker stories', text: 'Every product links to the artisan\'s profile, region and technique.' },
      { title: 'Artisan portal', text: 'A simple, mobile-friendly portal to list items and manage orders.' },
      { title: 'Courier integration', text: 'Automatic shipping labels and tracking through courier partners.' },
      { title: 'Transparent payouts', text: 'Sales and payout statements for every artisan.' },
    ],
    features: [
      { title: 'Shop by craft and region', text: 'Browse by technique, material or state.' },
      { title: 'Authenticity details', text: 'Materials, care instructions and craft origin on each page.' },
      { title: 'Gift options', text: 'Gift wrap and personal notes at checkout.' },
      { title: 'Low-stock badges', text: 'Clear signals for one-off and limited pieces.' },
      { title: 'Reviews with photos', text: 'Shoppers share how pieces look in real life.' },
    ],
    outcomes: [
      { title: 'New market for makers', text: 'Artisans reach buyers far beyond local fairs.' },
      { title: 'Stronger brand', text: 'Stories make handmade value visible.' },
      { title: 'Reliable delivery', text: 'Integrated shipping reduces damage and delays.' },
      { title: 'Fair and clear payments', text: 'Makers always know what they have earned.' },
    ],
  },
  {
    slug: 'paynest-digital-wallet-app',
    name: 'PayNest',
    title: 'Digital wallet for bills, transfers and everyday payments',
    category: 'Mobile Apps',
    industry: 'Fintech',
    platforms: ['Android App', 'iOS App', 'Admin Panel'],
    accent: '#047857',
    shots: { hero: 3, feature: 2 },
    summary:
      'PayNest is a wallet app concept for everyday payments: utility bills, mobile recharges, parking, and sending money to friends. It focuses on security, a clean interface, and spending insights that help users understand where their money goes.',
    stack: ['Kotlin', 'Swift', 'Node.js', 'PostgreSQL', 'Redis', 'Payment gateway APIs'],
    challenges: [
      { title: 'Security concerns', text: 'Users hesitate to keep money in apps they do not fully trust.' },
      { title: 'Too many apps', text: 'Bills, recharges and transfers are spread across different apps.' },
      { title: 'Confusing interfaces', text: 'Cluttered screens make simple payments feel complicated.' },
      { title: 'Failed transactions', text: 'Payments that fail without clear status cause anxiety and support calls.' },
      { title: 'No spending insight', text: 'Users cannot easily see where their money goes each month.' },
      { title: 'Regulatory compliance', text: 'KYC, limits and audit trails must be built in from the start.' },
    ],
    solutions: [
      { title: 'Layered security', text: 'Biometric login, device binding, PIN and real-time fraud checks.' },
      { title: 'All payments in one place', text: 'Bills, recharges, parking and transfers from one home screen.' },
      { title: 'Clear transaction status', text: 'Live status, receipts and automatic refunds for failed payments.' },
      { title: 'Spending insights', text: 'Monthly charts and categories that make budgeting simple.' },
    ],
    features: [
      { title: 'Bill reminders', text: 'Never miss electricity, water or broadband due dates.' },
      { title: 'Send and request money', text: 'Pay contacts or split bills in a few taps.' },
      { title: 'Scan and pay', text: 'QR payments at shops and parking lots.' },
      { title: 'e-KYC onboarding', text: 'Quick digital verification to unlock full limits.' },
      { title: 'Support chat', text: 'Help with any transaction from inside the app.' },
    ],
    outcomes: [
      { title: 'Trust by design', text: 'Security features users can see and understand.' },
      { title: 'Convenience', text: 'Everyday payments handled in one app.' },
      { title: 'Fewer support tickets', text: 'Clear status and auto-refunds answer most questions.' },
      { title: 'Compliance-ready', text: 'KYC, limits and logs built into the core.' },
    ],
  },
  {
    slug: 'gatepass-visitor-management',
    name: 'GatePass',
    title: 'Visitor and gate management for residential societies',
    category: 'Enterprise Software',
    industry: 'Real Estate & Facilities',
    platforms: ['Guard Tablet App', 'Resident App', 'Web Admin'],
    accent: '#1F3C88',
    shots: { hero: 2, feature: 3 },
    summary:
      'GatePass replaces paper visitor registers at apartment gates. Guards check in guests, deliveries and staff on a tablet, residents approve entries from their phone, and the committee gets a searchable log of everyone who came in and out.',
    stack: ['React Native', 'React', 'Node.js', 'PostgreSQL', 'Firebase Cloud Messaging'],
    challenges: [
      { title: 'Paper registers', text: 'Handwritten entries are slow, illegible and easy to fake.' },
      { title: 'Calling residents', text: 'Guards phone flats to confirm every visitor, creating queues at the gate.' },
      { title: 'Delivery overload', text: 'Food and parcel deliveries flood the gate at peak hours.' },
      { title: 'Domestic staff tracking', text: 'Maids, drivers and cooks come and go with no attendance record.' },
      { title: 'Security gaps', text: 'There is no quick way to check who is inside during an emergency.' },
      { title: 'Searching old records', text: 'Finding a past entry means flipping through registers.' },
    ],
    solutions: [
      { title: 'Tablet check-in', text: 'Guards capture name, photo and flat in seconds.' },
      { title: 'Approve from phone', text: 'Residents get a notification and approve or deny with one tap.' },
      { title: 'Pre-approved passes', text: 'Residents share QR passes for expected guests and regular staff.' },
      { title: 'Searchable digital log', text: 'Every entry and exit stored with time, photo and approver.' },
    ],
    features: [
      { title: 'Delivery handling', text: 'Leave-at-gate or allow-in options for deliveries.' },
      { title: 'Staff attendance', text: 'Entry and exit history for domestic help.' },
      { title: 'Emergency alerts', text: 'Residents and guards can raise an SOS instantly.' },
      { title: 'Notices and polls', text: 'Committee announcements in the resident app.' },
      { title: 'Reports for committee', text: 'Daily footfall and security reports.' },
    ],
    outcomes: [
      { title: 'Shorter gate queues', text: 'Approvals happen in seconds, not phone calls.' },
      { title: 'Safer premises', text: 'Every visitor is identified and recorded.' },
      { title: 'Happier residents', text: 'Control over who enters, from anywhere.' },
      { title: 'Paperless records', text: 'History is searchable in seconds.' },
    ],
  },
  {
    slug: 'dashdrop-same-day-courier-app',
    name: 'DashDrop',
    title: 'Same-day courier booking and delivery app',
    category: 'Mobile Apps',
    industry: 'Logistics',
    platforms: ['Customer App', 'Rider App', 'Admin Panel'],
    accent: '#C2410C',
    shots: { hero: 2, feature: 3 },
    summary:
      'DashDrop lets people and small businesses book a rider to pick up and deliver parcels across the city within hours. Customers see the price upfront and track the rider live, riders get optimised routes, and the admin team manages fleet and payouts.',
    stack: ['Flutter', 'Node.js', 'PostgreSQL', 'Redis', 'Google Maps Platform', 'Razorpay'],
    challenges: [
      { title: 'Unclear pricing', text: 'Customers do not know the cost until after a phone call.' },
      { title: 'No live tracking', text: 'Senders and receivers cannot see where their parcel is.' },
      { title: 'Inefficient routes', text: 'Riders waste time and fuel on poorly planned trips.' },
      { title: 'Proof of delivery', text: 'Disputes arise when there is no record of handover.' },
      { title: 'Rider management', text: 'Assigning jobs and tracking rider availability is manual.' },
      { title: 'Business customers', text: 'Shops need bulk bookings and monthly billing.' },
    ],
    solutions: [
      { title: 'Instant quotes', text: 'Price calculated from distance, size and urgency before booking.' },
      { title: 'Live map tracking', text: 'Real-time rider location shared with sender and receiver.' },
      { title: 'Smart dispatch', text: 'Jobs auto-assigned to the nearest available rider with optimised routes.' },
      { title: 'Digital proof of delivery', text: 'Photo, OTP and signature captured at handover.' },
    ],
    features: [
      { title: 'Multi-stop deliveries', text: 'One pickup, several drop points in a single booking.' },
      { title: 'Scheduled pickups', text: 'Book now or choose a time slot.' },
      { title: 'Rider earnings dashboard', text: 'Trips, earnings and payouts for riders.' },
      { title: 'Business accounts', text: 'Bulk upload and monthly invoices for shops.' },
      { title: 'Ratings and support', text: 'Feedback after each delivery and in-app help.' },
    ],
    outcomes: [
      { title: 'Transparent service', text: 'Customers know the price and status at all times.' },
      { title: 'Efficient fleet', text: 'Better routing means more deliveries per rider.' },
      { title: 'Fewer disputes', text: 'Proof of delivery settles questions instantly.' },
      { title: 'B2B growth', text: 'Business accounts open steady, repeat demand.' },
    ],
  },
  {
    slug: 'fieldpro-service-operations',
    name: 'FieldPro',
    title: 'Installation and service management for field technicians',
    category: 'Enterprise Software',
    industry: 'Equipment & HVAC Services',
    platforms: ['Web Admin', 'Technician App', 'Customer Portal'],
    accent: '#0F766E',
    shots: { hero: 2, feature: 3 },
    summary:
      'FieldPro manages the full life of installed equipment such as air-conditioning units, generators and industrial machines: installation jobs, scheduled maintenance, breakdown tickets and annual maintenance contracts, with a mobile app for technicians in the field.',
    stack: ['React', 'React Native', 'Node.js', 'PostgreSQL', 'Firebase', 'Google Maps'],
    challenges: [
      { title: 'Paper job cards', text: 'Technicians fill paper forms that reach the office days later.' },
      { title: 'Missed maintenance', text: 'Scheduled services under contract are forgotten until the customer complains.' },
      { title: 'Poor dispatch', text: 'Jobs are assigned by phone without considering location or skills.' },
      { title: 'Spare parts usage', text: 'Parts used on site are not recorded, so stock and billing drift.' },
      { title: 'Customer updates', text: 'Customers do not know when a technician will arrive.' },
      { title: 'Contract renewals', text: 'AMC expiries are tracked in spreadsheets and renewals are missed.' },
    ],
    solutions: [
      { title: 'Digital job cards', text: 'Checklists, photos, parts used and customer signature captured in the app.' },
      { title: 'Automatic service schedules', text: 'Maintenance visits generated from each contract and asset.' },
      { title: 'Skill and location-based dispatch', text: 'Assign the right technician based on distance and expertise.' },
      { title: 'Customer portal', text: 'Customers raise tickets, see visit times and download reports.' },
    ],
    features: [
      { title: 'Asset register', text: 'Every installed unit with serial number and history.' },
      { title: 'Breakdown tickets', text: 'Priority-based ticketing with SLA timers.' },
      { title: 'Offline technician app', text: 'Works in basements and remote sites, syncs later.' },
      { title: 'Parts and inventory', text: 'Van stock and warehouse stock updated per job.' },
      { title: 'AMC renewal alerts', text: 'Reminders before contracts expire.' },
    ],
    outcomes: [
      { title: 'Faster closures', text: 'Jobs are closed on site, not days later.' },
      { title: 'Contracts honoured', text: 'No scheduled service is forgotten.' },
      { title: 'Accurate billing', text: 'Parts and labour recorded per job.' },
      { title: 'Better customer experience', text: 'Customers always know what is happening.' },
    ],
  },
  {
    slug: 'tradelink-distributor-ordering-app',
    name: 'TradeLink',
    title: 'Dealer ordering app for consumer goods distributors',
    category: 'Mobile Apps',
    industry: 'FMCG Distribution',
    platforms: ['Android App', 'Web Admin'],
    accent: '#1F3C88',
    shots: { hero: 2, feature: 3 },
    summary:
      'TradeLink lets retailers and dealers order stock directly from a distributor on their phone: browse the catalogue, see their own prices and schemes, place orders, track deliveries and check outstanding payments, without waiting for a sales rep visit.',
    stack: ['Kotlin', 'React', 'Node.js', 'PostgreSQL', 'Tally integration', 'Firebase'],
    challenges: [
      { title: 'Orders via calls and WhatsApp', text: 'Orders arrive in messages and get missed or mistyped.' },
      { title: 'Dealer-specific pricing', text: 'Every dealer has different prices, discounts and schemes.' },
      { title: 'Outstanding payments', text: 'Dealers do not know their current balance, and reps chase payments manually.' },
      { title: 'Catalogue updates', text: 'New products and price changes do not reach dealers on time.' },
      { title: 'Delivery tracking', text: 'Dealers keep calling to ask when stock will arrive.' },
      { title: 'Accounting sync', text: 'Orders are retyped into the accounting software.' },
    ],
    solutions: [
      { title: 'Personal catalogue', text: 'Each dealer sees their own prices, schemes and credit limit.' },
      { title: 'Quick re-ordering', text: 'Repeat past orders and add items in a few taps.' },
      { title: 'Ledger and payments', text: 'Live outstanding balance, invoices and payment records.' },
      { title: 'Accounting integration', text: 'Orders and invoices sync with the distributor\'s accounting system.' },
    ],
    features: [
      { title: 'Scheme and offer banners', text: 'Promotions pushed to dealers instantly.' },
      { title: 'Order status updates', text: 'Confirmed, packed, dispatched and delivered.' },
      { title: 'Credit limit checks', text: 'Orders checked against available credit.' },
      { title: 'Sales rep view', text: 'Reps place orders on behalf of dealers.' },
      { title: 'Regional language support', text: 'Easy for dealers across regions to use.' },
    ],
    outcomes: [
      { title: 'Error-free orders', text: 'No more lost or mistyped WhatsApp orders.' },
      { title: 'Faster collections', text: 'Dealers see and settle balances on time.' },
      { title: 'Less rep workload', text: 'Reps focus on growth, not order taking.' },
      { title: 'Connected back office', text: 'No double entry into accounts.' },
    ],
  },
  {
    slug: 'nestfinder-rental-property-platform',
    name: 'NestFinder',
    title: 'Rental property listing and tenant management platform',
    category: 'Mobile Apps',
    industry: 'Real Estate',
    platforms: ['Web App', 'Android App', 'iOS App'],
    accent: '#0369A1',
    shots: { hero: 2, feature: 3 },
    summary:
      'NestFinder helps tenants find verified rental homes and helps owners manage them after move-in. Tenants search on a map, schedule visits and sign agreements online; owners collect rent, log maintenance requests and keep documents in one place.',
    stack: ['React', 'React Native', 'Node.js', 'PostgreSQL', 'Mapbox', 'Razorpay'],
    challenges: [
      { title: 'Fake listings', text: 'Tenants waste visits on homes that are already let or do not match the photos.' },
      { title: 'Broker dependence', text: 'Searching without a broker is slow and frustrating.' },
      { title: 'Visit scheduling', text: 'Coordinating viewings between owners and tenants takes many calls.' },
      { title: 'Paper agreements', text: 'Rental agreements and KYC are handled on paper.' },
      { title: 'Rent collection', text: 'Owners track rent and deposits manually.' },
      { title: 'Maintenance requests', text: 'Repairs are requested by phone and forgotten.' },
    ],
    solutions: [
      { title: 'Verified listings', text: 'Owner verification and photo checks before a listing goes live.' },
      { title: 'Map-based search', text: 'Search by area, budget, commute and amenities on a map.' },
      { title: 'Visit booking', text: 'Tenants pick a slot from the owner\'s calendar.' },
      { title: 'Digital rental management', text: 'Online agreements, rent collection and maintenance tickets.' },
    ],
    features: [
      { title: 'Saved searches', text: 'Alerts for new homes matching your needs.' },
      { title: 'Virtual tours', text: '360° photos and video walkthroughs.' },
      { title: 'Rent reminders', text: 'Automatic reminders and receipts.' },
      { title: 'Document vault', text: 'Agreements and KYC stored securely.' },
      { title: 'Owner dashboard', text: 'Occupancy, rent and requests for every property.' },
    ],
    outcomes: [
      { title: 'Trustworthy search', text: 'Fewer wasted visits for tenants.' },
      { title: 'Less paperwork', text: 'Agreements and rent are handled online.' },
      { title: 'Organised owners', text: 'Every property managed from one dashboard.' },
      { title: 'Faster repairs', text: 'Requests are tracked until resolved.' },
    ],
  },
  {
    slug: 'campusly-school-erp',
    name: 'Campusly',
    title: 'School management ERP for admins, teachers and parents',
    category: 'Enterprise Software',
    industry: 'Education',
    platforms: ['Web App', 'Parent App', 'Teacher App'],
    accent: '#7C3AED',
    shots: { hero: 3, feature: 4 },
    summary:
      'Campusly brings a school\'s daily operations onto one platform: admissions, attendance, timetables, exams, fees and communication. Teachers save time on paperwork and parents follow their child\'s progress from a mobile app.',
    stack: ['React', 'Flutter', 'Node.js', 'PostgreSQL', 'Razorpay', 'Firebase'],
    challenges: [
      { title: 'Paper-based admin', text: 'Attendance, marks and fees are recorded in registers and spreadsheets.' },
      { title: 'Fee collection', text: 'Tracking dues and sending reminders takes staff days every term.' },
      { title: 'Parent communication', text: 'Circulars and updates get lost in diaries and group chats.' },
      { title: 'Report cards', text: 'Compiling marks into report cards is slow and error-prone.' },
      { title: 'Timetable clashes', text: 'Manual timetables lead to clashes and substitutions chaos.' },
      { title: 'Scattered data', text: 'Student information lives in different files across departments.' },
    ],
    solutions: [
      { title: 'Single student record', text: 'Admission to graduation in one profile.' },
      { title: 'Online fees', text: 'Fee plans, online payment, receipts and automatic reminders.' },
      { title: 'Parent app', text: 'Attendance, homework, results and circulars on the parent\'s phone.' },
      { title: 'Exam and report cards', text: 'Marks entry and auto-generated report cards.' },
    ],
    features: [
      { title: 'Quick attendance', text: 'Teachers mark attendance from their phone in seconds.' },
      { title: 'Timetable builder', text: 'Clash-free timetables and substitutions.' },
      { title: 'Homework and notes', text: 'Assignments shared with classes digitally.' },
      { title: 'Transport tracking', text: 'Bus routes and live location for parents.' },
      { title: 'Admin analytics', text: 'Attendance, fee and performance dashboards.' },
    ],
    outcomes: [
      { title: 'Less paperwork', text: 'Staff spend time on students, not registers.' },
      { title: 'On-time fees', text: 'Reminders and online payment improve collections.' },
      { title: 'Engaged parents', text: 'Parents stay informed every day.' },
      { title: 'Clear insights', text: 'Leadership sees the whole school at a glance.' },
    ],
  },
  {
    slug: 'portlane-freight-forwarding-website',
    name: 'PortLane',
    title: 'Corporate website with shipment tracking for a freight forwarder',
    category: 'Websites',
    industry: 'Shipping & Logistics',
    platforms: ['Website', 'Customer Portal'],
    accent: '#0F172A',
    shots: { hero: 3, feature: 2 },
    summary:
      'A corporate website concept for a freight forwarding company handling sea and air cargo. Besides presenting services and offices, it gives customers a portal to track shipments, download documents and request quotes online.',
    stack: ['Next.js', 'Tailwind CSS', 'Node.js', 'PostgreSQL', 'Headless CMS'],
    challenges: [
      { title: 'Information-only website', text: 'The old site lists services but offers customers nothing useful to do.' },
      { title: 'Tracking by email', text: 'Customers email operations staff for every shipment update.' },
      { title: 'Document requests', text: 'Bills of lading and invoices are sent manually on request.' },
      { title: 'Quote requests', text: 'Enquiries arrive incomplete and need several follow-ups.' },
      { title: 'Many locations', text: 'Offices and port contacts across cities are hard to find.' },
      { title: 'Brand credibility', text: 'An outdated design undersells the company\'s experience.' },
    ],
    solutions: [
      { title: 'Modern corporate site', text: 'Clear service pages for sea freight, air freight, customs and warehousing.' },
      { title: 'Shipment tracking', text: 'Track by container or booking number with milestone updates.' },
      { title: 'Customer document portal', text: 'Secure login to download shipment documents anytime.' },
      { title: 'Structured quote form', text: 'Captures route, cargo type and dates in one go.' },
    ],
    features: [
      { title: 'Office locator', text: 'All branches and port contacts on one map.' },
      { title: 'Industry pages', text: 'Solutions for pharma, automotive and retail cargo.' },
      { title: 'News and insights', text: 'Updates on routes, regulations and the company.' },
      { title: 'Careers section', text: 'Open roles and online applications.' },
      { title: 'Fast and accessible', text: 'Mobile-first, quick to load and easy to navigate.' },
    ],
    outcomes: [
      { title: 'Self-service customers', text: 'Tracking and documents without emailing staff.' },
      { title: 'Better enquiries', text: 'Complete quote requests reach sales faster.' },
      { title: 'Stronger brand', text: 'A site that matches the company\'s scale.' },
      { title: 'Lighter operations load', text: 'Fewer routine status calls and emails.' },
    ],
  },
  {
    slug: 'floodwatch-rainfall-monitoring-dashboard',
    name: 'FloodWatch',
    title: 'Rainfall and river-level monitoring dashboard',
    category: 'Enterprise Software',
    industry: 'Government & Disaster Management',
    platforms: ['Web Dashboard', 'Alert Service'],
    accent: '#0369A1',
    shots: { hero: 1, feature: 3 },
    summary:
      'FloodWatch brings rainfall gauges, river-level sensors and weather feeds onto one live map for district disaster-management teams. It visualises trends, highlights rising risk early, and sends alerts to officials and communities when thresholds are crossed.',
    stack: ['React', 'Leaflet', 'D3.js', 'Python', 'TimescaleDB', 'MQTT'],
    challenges: [
      { title: 'Data in silos', text: 'Rain gauges, river sensors and forecasts live in separate systems.' },
      { title: 'Hard-to-read data', text: 'Raw numbers and tables make it hard to see risk building up.' },
      { title: 'Late warnings', text: 'Alerts depend on someone noticing a threshold being crossed.' },
      { title: 'Sensor gaps', text: 'Offline sensors go unnoticed during critical periods.' },
      { title: 'Field coordination', text: 'Teams on the ground lack a shared picture of the situation.' },
      { title: 'Historical analysis', text: 'Past events are hard to replay and learn from.' },
    ],
    solutions: [
      { title: 'Unified live map', text: 'All sensors and forecasts layered on one interactive map.' },
      { title: 'Clear visualisations', text: 'Trend charts, colour-coded risk levels and rainfall heatmaps.' },
      { title: 'Automatic threshold alerts', text: 'SMS, email and app alerts when levels cross set limits.' },
      { title: 'Sensor health monitoring', text: 'Alerts when a station stops reporting.' },
    ],
    features: [
      { title: 'Time-slider replay', text: 'Replay rainfall and river levels over any period.' },
      { title: 'Risk zones', text: 'Villages and roads at risk highlighted on the map.' },
      { title: 'Mobile field view', text: 'A simplified map for teams on the ground.' },
      { title: 'Reports export', text: 'Daily situation reports in one click.' },
      { title: 'Role-based access', text: 'District, state and public views.' },
    ],
    outcomes: [
      { title: 'Earlier warnings', text: 'Rising risk is visible before it becomes an emergency.' },
      { title: 'Shared situational picture', text: 'Everyone works from the same live map.' },
      { title: 'Reliable sensor network', text: 'Offline stations are fixed quickly.' },
      { title: 'Better planning', text: 'Historical replays inform preparedness.' },
    ],
  },
  {
    slug: 'atelier-nine-interior-studio-website',
    name: 'Atelier Nine',
    title: 'Portfolio website for a premium interior design studio',
    category: 'Websites',
    industry: 'Interior Design',
    platforms: ['Website', 'CMS'],
    accent: '#44403C',
    shots: { hero: 2, feature: 1 },
    summary:
      'A website concept for a high-end interior design studio. Large, calm imagery puts completed homes and offices centre stage, project pages tell the story from brief to handover, and a refined enquiry flow captures serious leads.',
    stack: ['Next.js', 'Sanity CMS', 'Tailwind CSS', 'Vercel', 'Cloudinary'],
    challenges: [
      { title: 'Showing quality online', text: 'Premium work loses its impact on a generic template site.' },
      { title: 'Heavy photography', text: 'Large photo galleries make websites slow.' },
      { title: 'Telling project stories', text: 'Photos alone do not explain the design thinking behind a space.' },
      { title: 'Low-quality leads', text: 'Generic contact forms bring enquiries that are not a good fit.' },
      { title: 'Updating the portfolio', text: 'Adding a new project needs a developer.' },
      { title: 'Mobile experience', text: 'Wide imagery is hard to present well on small screens.' },
    ],
    solutions: [
      { title: 'Editorial design', text: 'Generous whitespace and full-width imagery that feel like a design magazine.' },
      { title: 'Optimised images', text: 'Responsive, lazy-loaded images that stay sharp and fast.' },
      { title: 'Project case studies', text: 'Brief, concept, materials and final reveal for each project.' },
      { title: 'Qualifying enquiry form', text: 'Asks for project type, size, location and timeline.' },
    ],
    features: [
      { title: 'Filter by space', text: 'Residential, hospitality and workplace projects.' },
      { title: 'Before and after sliders', text: 'Show the transformation of a space.' },
      { title: 'Services and process', text: 'How the studio works, step by step.' },
      { title: 'Easy CMS', text: 'The studio adds new projects themselves.' },
      { title: 'Instagram feed', text: 'Latest work pulled in automatically.' },
    ],
    outcomes: [
      { title: 'Premium first impression', text: 'The site reflects the quality of the work.' },
      { title: 'Better-fit enquiries', text: 'Leads arrive with the details the team needs.' },
      { title: 'Always up to date', text: 'New projects go live without developers.' },
      { title: 'Fast everywhere', text: 'Beautiful on mobile and desktop alike.' },
    ],
  },
  {
    slug: 'mindmove-fitness-mindfulness-app',
    name: 'MindMove',
    title: 'Fitness, habits and mindfulness tracking app',
    category: 'Mobile Apps',
    industry: 'Health & Wellness',
    platforms: ['iOS App', 'Android App'],
    accent: '#047857',
    shots: { hero: 2, feature: 3 },
    summary:
      'MindMove combines workouts, daily habits and short mindfulness sessions in one app. Users set goals, follow guided routines, track streaks and moods, and join friendly challenges with friends to stay consistent.',
    stack: ['React Native', 'Node.js', 'MongoDB', 'Apple HealthKit', 'Google Fit', 'Firebase'],
    challenges: [
      { title: 'Staying motivated', text: 'Most people drop new fitness routines within a few weeks.' },
      { title: 'Too many apps', text: 'Workouts, meditation and habit tracking live in separate apps.' },
      { title: 'One-size-fits-all plans', text: 'Generic plans do not fit different fitness levels or schedules.' },
      { title: 'Manual tracking', text: 'Logging every activity by hand is tedious.' },
      { title: 'Mental wellbeing ignored', text: 'Fitness apps rarely consider stress, sleep and mood.' },
      { title: 'Lonely journey', text: 'Without community, it is easy to give up.' },
    ],
    solutions: [
      { title: 'All-in-one daily plan', text: 'Workout, habits and a mindfulness session in one daily view.' },
      { title: 'Personalised goals', text: 'Plans adapt to the user\'s level, time and preferences.' },
      { title: 'Automatic tracking', text: 'Steps, workouts and sleep synced from HealthKit and Google Fit.' },
      { title: 'Social challenges', text: 'Join friends in streaks and weekly challenges.' },
    ],
    features: [
      { title: 'Guided workouts', text: 'Short video routines for home or gym.' },
      { title: 'Habit streaks', text: 'Water, sleep, reading or any custom habit.' },
      { title: 'Mood journal', text: 'Quick daily check-ins with trends over time.' },
      { title: 'Breathing sessions', text: 'Two to ten-minute guided mindfulness.' },
      { title: 'Progress reports', text: 'Weekly summaries to share or keep private.' },
    ],
    outcomes: [
      { title: 'Consistency', text: 'Streaks and challenges help habits stick.' },
      { title: 'Whole-person wellness', text: 'Body and mind tracked together.' },
      { title: 'Less effort', text: 'Automatic syncing removes manual logging.' },
      { title: 'Community support', text: 'Friends keep each other going.' },
    ],
  },
  {
    slug: 'rangoli-rush-puzzle-game',
    name: 'Rangoli Rush',
    title: 'Festival-themed match puzzle game for mobile',
    category: 'Games',
    industry: 'Casual Gaming',
    platforms: ['Android', 'iOS'],
    accent: '#C2410C',
    shots: { hero: 2, feature: 3 },
    summary:
      'Rangoli Rush is a colourful match-and-clear puzzle game inspired by Indian festivals. Players complete rangoli patterns across hundreds of short levels, unlock seasonal festival events, and compete with friends on weekly leaderboards.',
    stack: ['Unity', 'C#', 'Firebase', 'Google Play Games Services', 'Game Center', 'AdMob'],
    challenges: [
      { title: 'Crowded puzzle market', text: 'Match puzzles are everywhere, so a new game needs a fresh theme and feel.' },
      { title: 'Short play sessions', text: 'Players often have only a minute or two between other tasks.' },
      { title: 'Level difficulty', text: 'Levels that are too easy bore players and levels that are too hard make them quit.' },
      { title: 'Low-end phones', text: 'Many players use budget phones with limited memory and battery.' },
      { title: 'Keeping players returning', text: 'Most casual players stop after the first few days.' },
      { title: 'Fair monetisation', text: 'Ads and purchases must not feel pushy or pay-to-win.' },
    ],
    solutions: [
      { title: 'Distinctive cultural theme', text: 'Rangoli patterns, diya effects and festival music give the game its own identity.' },
      { title: 'Bite-sized levels', text: 'Most levels finish in under two minutes, ideal for quick breaks.' },
      { title: 'Data-tuned difficulty', text: 'Play analytics guide how each level is balanced after launch.' },
      { title: 'Lightweight build', text: 'Optimised graphics and small download size for budget devices.' },
    ],
    features: [
      { title: 'Seasonal festival events', text: 'Diwali, Holi and Pongal event levels with special rewards.' },
      { title: 'Daily challenges', text: 'A new puzzle every day with streak bonuses.' },
      { title: 'Friends leaderboard', text: 'Compare weekly scores with friends.' },
      { title: 'Offline play', text: 'Play anywhere and sync progress later.' },
      { title: 'Optional rewarded ads', text: 'Players choose when to watch an ad for a bonus.' },
    ],
    outcomes: [
      { title: 'Memorable identity', text: 'A theme that stands out in app store listings.' },
      { title: 'Habit-forming play', text: 'Daily challenges and events bring players back.' },
      { title: 'Wide reach', text: 'Runs smoothly on entry-level phones.' },
      { title: 'Player-friendly revenue', text: 'Monetisation that respects the player.' },
    ],
  },
  {
    slug: 'gully-strikers-cricket-game',
    name: 'Gully Strikers',
    title: 'Street-cricket arcade game with real-time multiplayer',
    category: 'Games',
    industry: 'Sports Gaming',
    platforms: ['Android', 'iOS', 'Web'],
    accent: '#047857',
    shots: { hero: 2, feature: 3 },
    summary:
      'Gully Strikers captures the fun of street cricket in quick arcade matches. Players build a team from their neighbourhood, play two-over matches against friends in real time, and climb city and national leagues.',
    stack: ['Unity', 'C#', 'Photon Multiplayer', 'Node.js', 'Redis', 'PlayFab'],
    challenges: [
      { title: 'Long matches', text: 'Full cricket games take too long for casual mobile sessions.' },
      { title: 'Complex controls', text: 'Realistic cricket controls are hard to learn on a touchscreen.' },
      { title: 'Real-time lag', text: 'Multiplayer must feel fair even on patchy mobile networks.' },
      { title: 'Finding opponents', text: 'Players wait too long for a match with someone of similar skill.' },
      { title: 'Cheating', text: 'Competitive leaderboards attract modified clients and fake scores.' },
      { title: 'Social sharing', text: 'Great shots disappear unless they are easy to share.' },
    ],
    solutions: [
      { title: 'Two-over arcade matches', text: 'Fast matches that finish in about three minutes.' },
      { title: 'Swipe-to-play controls', text: 'Simple swipes for shots and bowling, with depth for skilled players.' },
      { title: 'Lag-tolerant netcode', text: 'Turn-based ball exchanges keep play fair on slower connections.' },
      { title: 'Skill-based matchmaking', text: 'Players are paired by rating for close, exciting games.' },
    ],
    features: [
      { title: 'Friend challenges', text: 'Invite a friend to a match with a shareable link.' },
      { title: 'City leagues', text: 'Seasonal leagues by city and region.' },
      { title: 'Team customisation', text: 'Kits, bats and team names to make it yours.' },
      { title: 'Shot replays', text: 'Save and share your best sixes as short clips.' },
      { title: 'Server-side score checks', text: 'Results validated to keep leaderboards honest.' },
    ],
    outcomes: [
      { title: 'Easy to pick up', text: 'Anyone can play a match within seconds.' },
      { title: 'Social growth', text: 'Friend challenges and replays spread the game naturally.' },
      { title: 'Fair competition', text: 'Matchmaking and checks keep games enjoyable.' },
      { title: 'Long-term engagement', text: 'Leagues and seasons give players goals.' },
    ],
  },
  {
    slug: 'lexiquest-learning-game',
    name: 'LexiQuest',
    title: 'Word-adventure learning game for children',
    category: 'Games',
    industry: 'EdTech',
    platforms: ['Web', 'Android Tablet', 'iPad'],
    accent: '#7C3AED',
    shots: { hero: 2, feature: 1 },
    summary:
      'LexiQuest turns reading and vocabulary practice into an adventure. Children aged 6 to 12 explore story worlds by solving word puzzles, while parents and teachers follow progress from a simple dashboard.',
    stack: ['Phaser', 'TypeScript', 'React', 'Node.js', 'PostgreSQL', 'Text-to-speech API'],
    challenges: [
      { title: 'Practice feels like homework', text: 'Children lose interest in repetitive spelling and reading drills.' },
      { title: 'Different reading levels', text: 'Children in the same class read at very different levels.' },
      { title: 'Screen-time worries', text: 'Parents want learning value, not endless play.' },
      { title: 'No visibility for adults', text: 'Parents and teachers cannot see what a child has practised.' },
      { title: 'Child safety', text: 'Children\'s apps must avoid ads, chat and data collection risks.' },
      { title: 'Shared devices', text: 'Families and classrooms often share one tablet.' },
    ],
    solutions: [
      { title: 'Story-driven quests', text: 'Each word puzzle moves the story forward, so practice feels like play.' },
      { title: 'Adaptive difficulty', text: 'Puzzles adjust to each child\'s reading level automatically.' },
      { title: 'Healthy play limits', text: 'Parents set daily time limits and session reminders.' },
      { title: 'Progress dashboard', text: 'Words learned, accuracy and time spent for parents and teachers.' },
    ],
    features: [
      { title: 'Read-aloud support', text: 'Words and stories spoken aloud for early readers.' },
      { title: 'Multiple child profiles', text: 'Each child keeps their own progress on a shared device.' },
      { title: 'Classroom mode', text: 'Teachers assign word lists to a class.' },
      { title: 'No ads, no chat', text: 'A safe space designed for children.' },
      { title: 'Rewards and badges', text: 'Collectibles that celebrate progress.' },
    ],
    outcomes: [
      { title: 'Motivated learners', text: 'Children want to keep playing and practising.' },
      { title: 'Right level for each child', text: 'Adaptive puzzles avoid boredom and frustration.' },
      { title: 'Informed adults', text: 'Parents and teachers see real progress.' },
      { title: 'Trusted by families', text: 'Safety and time limits built in.' },
    ],
  },
];

export const getProject = (slug) => projects.find((p) => p.slug === slug);
