/**
 * Fullstackverse + SkillVerse form backend — Google Apps Script Web App
 *
 * Receives every form on www.fullstackverse.in (via src/lib/appsScript.js),
 * writes each one to its own tab in the bound Google Sheet, emails the team
 * about new leads, and sends event confirmation emails.
 *
 * Requests (POST, JSON body sent as text/plain; field `action` picks the handler):
 *   submit_contact      Business enquiry dialog, RFP form, SkillVerse Quick Apply,
 *                       Campus Ambassador application (routed by `type`)
 *   submit_webinar      Webinar / workshop / course registrations (`webinar_slug`)
 *   send_webinar_email  Confirmation email for a registered event
 * Every request also carries `source` ("<page title> (<path>)").
 * Responses are always HTTP 200 JSON: { success: boolean, message?: string }.
 *
 * SETUP
 * 1. Open the Google Sheet that should receive submissions.
 * 2. Extensions > Apps Script (the script is bound to that sheet).
 * 3. Replace the editor contents with this file and save.
 * 4. Deploy > New deployment > Web app; Execute as: Me; Who has access: Anyone.
 * 5. Run testBusinessEnquiry once from the editor and approve the
 *    Sheets + Gmail permissions it asks for (the web app cannot ask visitors).
 * 6. Put the /exec URL in site_config.py (FORMS["apps_script_url"]) and the
 *    GitHub variable VITE_GOOGLE_APPS_SCRIPT_URL.
 * A standalone script (created at script.google.com) also needs
 * FORMS["spreadsheet_id"] in site_config.py.
 * To update an existing deployment: Deploy > Manage deployments > edit >
 * Version: New version > Deploy (the URL stays the same).
 * Run the test* functions below from the editor to check each form type.
 */

// ---- BEGIN CONFIG (generated by `python3 site_config.py`; edit there) ----
const CONFIG = {
  "brand": "Fullstackverse",
  "spreadsheetId": "1jlGzulcP7h8yuVzm1I_MPHQcpOTSigJ94qz5ET63Rtw",
  "notifyEmail": "info@fullstackverse.in",
  "notifyOnSubmit": true,
  "senderName": "SkillVerse by Fullstackverse",
  "replyTo": "info@fullstackverse.in",
  "website": "https://www.fullstackverse.in",
  "events": {
    "ai-agent-human-intern": {
      "title": "Build Your First AI Agent"
    },
    "robotics-workshop": {
      "title": "Build Your First Robot"
    },
    "study-usa-green-card-roadmap": {
      "title": "USA Webinar \u2013 SkillVerse Masterclass",
      "date": "Saturday, 14 February",
      "time": "11:00 AM \u2013 1:00 PM",
      "timezone": "Asia/Kolkata",
      "meetUrl": "https://meet.google.com/buw-yewo-zxr",
      "whatsappGroup": "https://chat.whatsapp.com/GK4oAZtp21oGvkEGyZvku1?mode=gi_t"
    },
    "competitive-exam-masterclass": {
      "title": "Master Competitive Exams"
    },
    "speak-english-confidently": {
      "title": "Speak English Confidently"
    },
    "data-science-course": {
      "title": "Paid Data Science Internship Program"
    }
  }
};
// ---- END CONFIG ----

/* ============================
   SHEETS (one tab per form)
   ============================ */

const SHEETS = {
  enquiries: {
    name: 'Business Enquiries',
    headers: ['Timestamp', 'Form', 'Full Name', 'Email', 'Phone', 'Budget', 'Project Description', 'Source'],
  },
  applications: {
    name: 'SkillVerse Applications',
    headers: ['Timestamp', 'Full Name', 'Email', 'Phone', 'Service', 'Source'],
  },
  ambassadors: {
    name: 'Campus Ambassadors',
    headers: ['Timestamp', 'Full Name', 'Email', 'Phone', 'College', 'Course', 'Year', 'Why Join', 'Source'],
  },
  registrations: {
    name: 'Event Registrations',
    headers: ['Timestamp', 'Event', 'Event Title', 'Name', 'Email', 'Phone', 'Source'],
  },
};

// `type` values sent by the website, mapped to a readable form name.
const CONTACT_TYPES = {
  business: 'Business Enquiry',
  rfp: 'Request for Proposal',
  'SkillVerse Quick Apply': 'SkillVerse Quick Apply',
  'Campus Ambassador Application': 'Campus Ambassador',
};

/* ============================
   ENTRY POINTS
   ============================ */

function doPost(e) {
  try {
    const p = parseBody(e);
    if (!p) return json({ success: false, message: 'No JSON payload found in request body.' });

    switch (p.action) {
      case 'submit_webinar':
        return handleRegistration(p);
      case 'send_webinar_email':
        return handleConfirmationEmail(p);
      case 'submit_contact':
      default:
        return handleContact(p);
    }
  } catch (err) {
    Logger.log('doPost error: ' + (err && err.stack ? err.stack : err));
    return json({ success: false, message: 'Server error. Please try again or contact us directly.' });
  }
}

// Health check: open the /exec URL in a browser.
function doGet() {
  return json({ success: true, service: CONFIG.brand + ' forms', forms: Object.keys(SHEETS) });
}

/* ============================
   CONTACT-STYLE FORMS
   ============================ */

function handleContact(p) {
  const name = str(p.full_name);
  const email = str(p.email);
  const phone = digits(p.contact_number);

  const error = validate(name, email, phone);
  if (error) return json({ success: false, message: error });

  const type = str(p.type) || 'business';
  const formName = CONTACT_TYPES[type] || type;

  if (type === 'Campus Ambassador Application') {
    append(SHEETS.ambassadors, [now(), name, email, phone, str(p.college), str(p.course), str(p.year), str(p.why_join) || str(p.project_description), str(p.source)]);
  } else if (type === 'SkillVerse Quick Apply') {
    const service = str(p.service) || str(p.project_description).replace(/^Service interested:\s*/i, '');
    append(SHEETS.applications, [now(), name, email, phone, service, str(p.source)]);
  } else {
    if (!str(p.project_description)) return json({ success: false, message: 'Project description is required' });
    append(SHEETS.enquiries, [now(), formName, name, email, phone, str(p.budget), str(p.project_description), str(p.source)]);
  }

  notifyTeam(formName, [
    ['Name', name],
    ['Email', email],
    ['Phone', phone],
    ['Service', str(p.service)],
    ['College', str(p.college)],
    ['Course / Year', [str(p.course), str(p.year)].filter(Boolean).join(' · ')],
    ['Budget', type === 'rfp' ? str(p.budget) : ''],
    ['Details', str(p.why_join) || str(p.project_description)],
    ['Page', str(p.source)],
  ], email);

  return json({ success: true, message: 'Form submitted successfully' });
}

/* ============================
   EVENT REGISTRATIONS
   ============================ */

function handleRegistration(p) {
  const name = str(p.name);
  const email = str(p.email);
  const phone = digits(p.phone);
  const slug = str(p.webinar_slug);

  const error = validate(name, email, phone);
  if (error) return json({ success: false, message: error });
  if (!slug) return json({ success: false, message: 'Event is missing' });

  const event = CONFIG.events[slug] || {};
  append(SHEETS.registrations, [now(), slug, event.title || slug, name, email, phone, str(p.source)]);

  notifyTeam('Registration: ' + (event.title || slug), [
    ['Name', name],
    ['Email', email],
    ['Phone', phone],
    ['Page', str(p.source)],
  ], email);

  return json({ success: true, message: 'Registration submitted successfully' });
}

/* ============================
   EVENT CONFIRMATION EMAIL
   ============================ */

function handleConfirmationEmail(p) {
  const email = str(p.email);
  const name = str(p.name);
  // The USA webinar page is the original caller and does not always send a slug.
  const slug = str(p.webinar_slug) || 'study-usa-green-card-roadmap';
  const event = CONFIG.events[slug];

  if (!isValidEmail(email)) return json({ success: false, message: 'Valid email is required' });
  if (!event) return json({ success: false, message: 'Unknown event' });

  try {
    MailApp.sendEmail({
      to: email,
      subject: "🎓 You're Registered! " + event.title,
      htmlBody: confirmationHtml(name, event),
      name: CONFIG.senderName,
      replyTo: CONFIG.replyTo,
    });
    return json({ success: true });
  } catch (err) {
    Logger.log('confirmation email error: ' + (err && err.stack ? err.stack : err));
    return json({ success: false, message: 'Failed to send email' });
  }
}

function confirmationHtml(name, event) {
  const button = (href, label, bg) =>
    '<a href="' + href + '" style="display:inline-block;padding:12px 18px;background:' + bg + ';color:#F4F1EB;text-decoration:none;border-radius:3px;font-weight:bold;">' + label + '</a>';
  const details = event.date
    ? '<h3 style="font-family:Georgia,serif;font-weight:normal">Event details</h3>'
      + '<p><b>Date:</b> ' + esc(event.date) + '<br/><b>Time:</b> ' + esc(event.time || '') + '<br/><b>Time zone:</b> ' + esc(event.timezone || '') + '</p>'
    : '';
  return ''
    + '<div style="font-family:Arial,sans-serif;background:#F4F1EB;padding:25px;color:#211F1A">'
    + '  <div style="max-width:600px;margin:auto;background:#FAF8F4;border:1px solid #D9D2C7;padding:30px">'
    + '    <h2 style="font-family:Georgia,serif;font-weight:normal;margin-top:0">Welcome ' + esc(name || 'to SkillVerse') + '</h2>'
    + '    <p>Your registration for <b>' + esc(event.title) + '</b> is confirmed.</p>'
    + '    <hr style="border:0;border-top:1px solid #D9D2C7"/>'
    + details
    + (event.meetUrl ? '<p>' + button(event.meetUrl, '▶ Join Google Meet', '#211F1A') + '</p>' : '')
    + (event.whatsappGroup
      ? '<hr style="border:0;border-top:1px solid #D9D2C7;margin:25px 0"/><h3 style="font-family:Georgia,serif;font-weight:normal">Mandatory</h3>'
        + '<p>Join our WhatsApp group for updates, tips & community support.</p>'
        + '<p>' + button(event.whatsappGroup, '👉 Join WhatsApp Group', '#3A3630') + '</p>'
      : '')
    + '    <hr style="border:0;border-top:1px solid #D9D2C7;margin:25px 0"/>'
    + '    <p style="font-size:14px;color:#686158">Please join 5 minutes early.<br/>See you there!</p>'
    + '    <b>Team SkillVerse</b>'
    + '  </div>'
    + '</div>';
}

/* ============================
   TEAM NOTIFICATION
   ============================ */

function notifyTeam(formName, rows, replyTo) {
  if (!CONFIG.notifyOnSubmit || !CONFIG.notifyEmail) return;
  try {
    const body = rows
      .filter((r) => r[1])
      .map((r) => '<tr><td style="padding:4px 12px 4px 0;color:#686158">' + esc(r[0]) + '</td><td style="padding:4px 0">' + esc(r[1]) + '</td></tr>')
      .join('');
    MailApp.sendEmail({
      to: CONFIG.notifyEmail,
      subject: 'New ' + formName + ' — ' + CONFIG.brand + ' website',
      htmlBody: '<p>A new <b>' + esc(formName) + '</b> was submitted on the website.</p><table style="font-family:Arial,sans-serif;font-size:14px">' + body + '</table>',
      name: CONFIG.brand + ' website',
      replyTo: isValidEmail(replyTo) ? replyTo : CONFIG.replyTo,
    });
  } catch (err) {
    // A failed notification must never fail the visitor's submission.
    Logger.log('notifyTeam error: ' + (err && err.stack ? err.stack : err));
  }
}

/* ============================
   HELPERS
   ============================ */

function append(sheetDef, row) {
  const lock = LockService.getScriptLock();
  lock.waitLock(10000);
  try {
    getOrCreateSheet(sheetDef).appendRow(row);
  } finally {
    lock.releaseLock();
  }
}

// The bound spreadsheet, or the one named by CONFIG.spreadsheetId for a standalone script.
function getSpreadsheet() {
  if (CONFIG.spreadsheetId) return SpreadsheetApp.openById(CONFIG.spreadsheetId);
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  if (!ss) {
    throw new Error('No spreadsheet: open this script from the Sheet (Extensions > Apps Script) or set spreadsheet_id in site_config.py.');
  }
  return ss;
}

function getOrCreateSheet(def) {
  const ss = getSpreadsheet();
  let sheet = ss.getSheetByName(def.name);
  if (!sheet) {
    sheet = ss.insertSheet(def.name);
    sheet.appendRow(def.headers);
    sheet.getRange(1, 1, 1, def.headers.length).setFontWeight('bold').setBackground('#EAE4DA');
    sheet.setFrozenRows(1);
  }
  return sheet;
}

function validate(name, email, phone) {
  if (!name) return 'Full name is required';
  if (!isValidEmail(email)) return 'Valid email is required';
  if (phone.length < 6 || phone.length > 20) return 'A valid contact number is required';
  return '';
}

function parseBody(e) {
  if (!e || !e.postData || !e.postData.contents) return null;
  try {
    const parsed = JSON.parse(e.postData.contents);
    return parsed && typeof parsed === 'object' ? parsed : null;
  } catch (err) {
    return null;
  }
}

function str(v) {
  return v === null || v === undefined ? '' : String(v).trim();
}

function digits(v) {
  return str(v).replace(/\D/g, '');
}

function now() {
  return new Date();
}

function isValidEmail(v) {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v);
}

function esc(v) {
  return String(v).replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));
}

function json(obj) {
  return ContentService.createTextOutput(JSON.stringify(obj)).setMimeType(ContentService.MimeType.JSON);
}

/* ============================
   TESTS (run from the editor toolbar; check the sheet tabs and Executions log)
   ============================ */

function post_(payload) {
  return doPost({ postData: { contents: JSON.stringify(Object.assign({ source: 'Editor test' }, payload)) } }).getContent();
}

function testBusinessEnquiry() {
  Logger.log(post_({ action: 'submit_contact', type: 'business', full_name: 'Test User', email: 'test@example.com', contact_number: '9876543210', project_description: 'Test enquiry', budget: null }));
}

function testRfp() {
  Logger.log(post_({ action: 'submit_contact', type: 'rfp', full_name: 'Test User', email: 'test@example.com', contact_number: '9876543210', project_description: 'Test RFP', budget: '$5,000 - $10,000' }));
}

function testQuickApply() {
  Logger.log(post_({ action: 'submit_contact', type: 'SkillVerse Quick Apply', full_name: 'Test Student', email: 'test@example.com', contact_number: '9876543210', service: 'Data Science', project_description: 'Service interested: Data Science', budget: 'To be discussed' }));
}

function testCampusAmbassador() {
  Logger.log(post_({ action: 'submit_contact', type: 'Campus Ambassador Application', full_name: 'Test Student', email: 'test@example.com', contact_number: '9876543210', college: 'Test College', course: 'B.Tech', year: '3rd Year', why_join: 'Testing', budget: 'Campus Ambassador' }));
}

function testRegistration() {
  Logger.log(post_({ action: 'submit_webinar', webinar_slug: 'study-usa-green-card-roadmap', name: 'Test User', email: 'test@example.com', phone: '9876543210' }));
}

function testConfirmationEmail() {
  // Sends a real email: change the address to your own before running.
  Logger.log(post_({ action: 'send_webinar_email', webinar_slug: 'study-usa-green-card-roadmap', name: 'Test User', email: 'test@example.com' }));
}
