#!/usr/bin/env python3
"""Single source of truth for Fullstackverse business details and form settings.

Edit the values below, then run:

    python3 site_config.py

which regenerates:
  * src/lib/contact.js        contact details used by headers, footers and pages
  * code.gs (CONFIG block)    settings for the Google Apps Script form backend
  * .env                      VITE_GOOGLE_APPS_SCRIPT_URL for local development

The live site reads the Apps Script URL from the GitHub repository variable
VITE_GOOGLE_APPS_SCRIPT_URL at build time; the script prints the command to
update it when the URL here changes. After editing code.gs settings, paste the
new code.gs into the Apps Script editor and deploy a new version.
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent

SITE = {
    "name": "Fullstackverse",
    "tagline": "Your End-to-End Digital Partner",
    "domain": "https://www.fullstackverse.in",
    "custom_domain": "www.fullstackverse.in",

    # Main phone: calls, footers, enquiry WhatsApp
    "phone": "8296548156",
    "whatsapp": "918296548156",
    # SkillVerse header "Call" button uses a second line
    "skillverse_call": "7042709578",

    # One email address everywhere on the site
    "email": "info@fullstackverse.in",
    "address_lines": ["Digital Innovation Hub", "India"],

    # Prefilled WhatsApp messages
    "whatsapp_message": "Hello Fullstackverse, I'd like to discuss my project idea.",
    "skillverse_whatsapp_message": "Hello SkillVerse, I'd like to learn more about your courses.",
}

# Form backend: Google Apps Script web app (code.gs).
FORMS = {
    # /exec URL from Deploy > Manage deployments in the Apps Script editor.
    "apps_script_url": "https://script.google.com/macros/s/AKfycbwXappZKoZRh6IC7LDwxnEax0qz7vdnUxSGFllQSngi8V-5Ip-P17gC3KDSCdoYemTL/exec",

    # Google Sheet that receives submissions: the ID between /d/ and /edit in its URL.
    # Leave empty only if code.gs is opened from that Sheet (Extensions > Apps Script).
    "spreadsheet_id": "1jlGzulcP7h8yuVzm1I_MPHQcpOTSigJ94qz5ET63Rtw",

    # Email the team about every new submission (set to False to turn off).
    "notify_on_submit": True,
    "notify_email": SITE["email"],
    "sender_name": "SkillVerse by Fullstackverse",
    "reply_to": SITE["email"],

    # Events registered via `submit_webinar`, keyed by the page's webinar_slug.
    # date/time/meet_url/whatsapp_group are only needed for events that send a
    # confirmation email (currently the USA webinar).
    "events": {
        "ai-agent-human-intern": {"title": "Build Your First AI Agent"},
        "robotics-workshop": {"title": "Build Your First Robot"},
        "study-usa-green-card-roadmap": {
            "title": "USA Webinar – SkillVerse Masterclass",
            "date": "Saturday, 14 February",
            "time": "11:00 AM – 1:00 PM",
            "timezone": "Asia/Kolkata",
            "meet_url": "https://meet.google.com/buw-yewo-zxr",
            "whatsapp_group": "https://chat.whatsapp.com/GK4oAZtp21oGvkEGyZvku1?mode=gi_t",
        },
        "competitive-exam-masterclass": {"title": "Master Competitive Exams"},
        "speak-english-confidently": {"title": "Speak English Confidently"},
        "data-science-course": {"title": "Paid Data Science Internship Program"},
    },
}


# --------------------------------------------------------------------------
# Generators
# --------------------------------------------------------------------------

def _wa_url(number, message):
    from urllib.parse import quote
    return f"https://wa.me/{number}?text={quote(message, safe=',')}"


def contact_js():
    s = SITE
    js = lambda v: json.dumps(v, ensure_ascii=False)
    return f"""// Business contact details. GENERATED by `python3 site_config.py`; edit site_config.py.
export const PHONE = {js(s['phone'])};
export const EMAIL = {js(s['email'])};
export const ADDRESS_LINES = {js(s['address_lines'])};

// Main-site WhatsApp chat (header, footer).
export const WHATSAPP_URL =
  {js(_wa_url(s['whatsapp'], s['whatsapp_message']))};

// SkillVerse uses a second line for calls from its header.
export const SKILLVERSE_CALL = {js(s['skillverse_call'])};
export const SKILLVERSE_WHATSAPP_URL =
  {js(_wa_url(s['whatsapp'], s['skillverse_whatsapp_message']))};
"""


def gs_config():
    events = {}
    for slug, ev in FORMS["events"].items():
        out = {"title": ev["title"]}
        for src, dst in (("date", "date"), ("time", "time"), ("timezone", "timezone"),
                         ("meet_url", "meetUrl"), ("whatsapp_group", "whatsappGroup")):
            if ev.get(src):
                out[dst] = ev[src]
        events[slug] = out
    cfg = {
        "brand": SITE["name"],
        "spreadsheetId": FORMS.get("spreadsheet_id", ""),
        "notifyEmail": FORMS["notify_email"],
        "notifyOnSubmit": FORMS["notify_on_submit"],
        "senderName": FORMS["sender_name"],
        "replyTo": FORMS["reply_to"],
        "website": SITE["domain"],
        "events": events,
    }
    return "const CONFIG = " + json.dumps(cfg, indent=2) + ";"


def write_if_changed(path, text):
    old = path.read_text() if path.exists() else None
    if old != text:
        path.write_text(text)
        return True
    return False


def main():
    changed = []

    if write_if_changed(ROOT / "src/lib/contact.js", contact_js()):
        changed.append("src/lib/contact.js")

    gs_path = ROOT / "code.gs"
    gs = gs_path.read_text()
    pattern = re.compile(r"(// ---- BEGIN CONFIG[^\n]*\n).*?(\n// ---- END CONFIG ----)", re.S)
    if not pattern.search(gs):
        sys.exit("code.gs: CONFIG markers not found")
    if write_if_changed(gs_path, pattern.sub(lambda m: m.group(1) + gs_config() + m.group(2), gs)):
        changed.append("code.gs")

    env_path = ROOT / ".env"
    env = env_path.read_text() if env_path.exists() else ""
    line = f"VITE_GOOGLE_APPS_SCRIPT_URL={FORMS['apps_script_url']}"
    env = re.sub(r"^VITE_GOOGLE_APPS_SCRIPT_URL=.*$", line, env, flags=re.M) if "VITE_GOOGLE_APPS_SCRIPT_URL=" in env else env.rstrip("\n") + ("\n" if env else "") + line + "\n"
    if write_if_changed(env_path, env):
        changed.append(".env")

    print("Updated: " + (", ".join(changed) if changed else "nothing (already in sync)"))
    if "code.gs" in changed:
        print("Next: paste code.gs into the Apps Script editor and deploy a new version.")
    print("Live site URL variable (run if the URL changed):")
    print(f"  gh variable set VITE_GOOGLE_APPS_SCRIPT_URL --body '{FORMS['apps_script_url']}'")


if __name__ == "__main__":
    main()
