import React from 'react';
import { asset } from '@/lib/utils';
import { cn } from '@/lib/utils';

// Screenshot of a project's demo dashboard in a slim browser frame.
// Images are generated by `npm run screens` into public/portfolio/.
//   use 'hero' or 'feature' picks the view set in the project's `shots`
//   size 'sm' = card thumbnail, 'lg' = full width
export default function ProjectShot({ project, use = 'hero', size = 'lg', className, eager = false }) {
  const view = project.shots?.[use] || 1;
  const file = `${project.slug}-${view}${size === 'sm' ? '-sm' : ''}.webp`;
  const host = `${project.name.toLowerCase().replace(/[^a-z0-9]+/g, '')}.app`;
  return (
    <figure className={cn('overflow-hidden border border-line bg-surface', className)}>
      <div className="flex items-center gap-1.5 border-b border-line bg-surface-alt/60 px-3 py-2" aria-hidden="true">
        <span className="h-2 w-2 rounded-full bg-line-dark" />
        <span className="h-2 w-2 rounded-full bg-line-dark" />
        <span className="h-2 w-2 rounded-full bg-line-dark" />
        <span className="mono ml-3 truncate !text-[10px] text-ink-3">{host}</span>
        <span className="meta ml-auto hidden !text-[9px] sm:inline">Sample data</span>
      </div>
      <img
        src={asset(`portfolio/${file}`)}
        alt={`${project.name} dashboard${use === 'feature' ? ' (feature view)' : ''}`}
        width={size === 'sm' ? 880 : 1600}
        height={size === 'sm' ? 550 : 1000}
        loading={eager ? 'eager' : 'lazy'}
        decoding="async"
        className="block aspect-[16/10] w-full object-cover object-top"
      />
    </figure>
  );
}
